export const MAIN_NFT_ADDRESS = "<MAIN_COLLECTION_CONTRACT_ADDRESS>";
export const BURN_NFT_ADDRESS = "<BURN_COLLECTION_CONTRACT_ADDRESS>";
export const BURNTOCLAIM_NFT_ADDRESS = "<BURNTOCLAIM_COLLECTION_CONTRACT_ADDRESS>";